#include "engine/content/rbxlx_loader.h"
#include "engine/scene/part.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <math.h>

static char* read_file(const char* path,size_t* out_size){FILE* f;long size;char* data;if(!path||!out_size)return NULL;f=fopen(path,"rb");if(!f)return NULL;if(fseek(f,0,SEEK_END)!=0){fclose(f);return NULL;}size=ftell(f);if(size<0||size>64L*1024L*1024L){fclose(f);return NULL;}if(fseek(f,0,SEEK_SET)!=0){fclose(f);return NULL;}data=(char*)malloc((size_t)size+1);if(!data){fclose(f);return NULL;}if(fread(data,1,(size_t)size,f)!=(size_t)size){free(data);fclose(f);return NULL;}data[size]='\0';fclose(f);*out_size=(size_t)size;return data;}
static const char* find_item_end(const char* begin,const char* end){const char* p=begin;int depth=1;while(p<end){const char* open=strstr(p,"<Item");const char* close=strstr(p,"</Item>");if(!close)return NULL;if(open&&open<close){++depth;p=open+5;}else{--depth;p=close+7;if(depth==0)return p;}}return NULL;}
static int attr_value(const char* item,const char* item_end,const char* name,char* out,size_t out_size){char needle[64];const char* q;snprintf(needle,sizeof(needle),"%s=\"",name);q=strstr(item,needle);if(!q||q>=item_end)return 0;q+=strlen(needle);{const char* quote=strchr(q,'\"');size_t n;if(!quote||quote>item_end)return 0;n=(size_t)(quote-q);if(n>=out_size)n=out_size-1;memcpy(out,q,n);out[n]='\0';}return 1;}
static int named_text(const char* begin,const char* end,const char* tag,const char* name,char* out,size_t out_size){char open[128];const char* p;const char* gt;const char* close;size_t n;snprintf(open,sizeof(open),"<%s name=\"%s\"",tag,name);p=strstr(begin,open);if(!p||p>=end)return 0;gt=strchr(p,'>');if(!gt||gt>=end)return 0;++gt;close=strstr(gt,"</");if(!close||close>=end)return 0;n=(size_t)(close-gt);while(n&&isspace((unsigned char)*gt)){++gt;--n;}while(n&&isspace((unsigned char)gt[n-1]))--n;if(n>=out_size)n=out_size-1;memcpy(out,gt,n);out[n]='\0';return 1;}
static float named_float(const char* begin,const char* end,const char* tag,const char* name,float fallback){char text[64];char* ep;float v;if(!named_text(begin,end,tag,name,text,sizeof(text)))return fallback;v=strtof(text,&ep);return ep!=text?v:fallback;}
static int named_bool(const char* begin,const char* end,const char* name,int fallback){char text[32];if(!named_text(begin,end,"bool",name,text,sizeof(text)))return fallback;return strcmp(text,"true")==0?1:strcmp(text,"false")==0?0:fallback;}
static float component(const char* begin,const char* end,const char* tag,float fallback){char open[32];const char* p;const char* gt;const char* close;char text[64];char* ep;size_t n;float v;snprintf(open,sizeof(open),"<%s>",tag);p=strstr(begin,open);if(!p||p>=end)return fallback;gt=p+strlen(open);close=strstr(gt,"</");if(!close||close>=end)return fallback;n=(size_t)(close-gt);if(n>=sizeof(text))n=sizeof(text)-1;memcpy(text,gt,n);text[n]='\0';v=strtof(text,&ep);return ep!=text?v:fallback;}
static void cframe(const char* begin,const char* end,float* x,float* y,float* z,float* rx,float* ry,float* rz){const char* p=strstr(begin,"<CoordinateFrame name=\"CFrame\"");const char* q;float r00,r10,r20,r21,r22,r11,r12;if(!p||p>=end){*x=*y=*z=*rx=*ry=*rz=0;return;}q=strstr(p,"</CoordinateFrame>");if(!q||q>=end)q=end;*x=component(p,q,"X",0);*y=component(p,q,"Y",0);*z=component(p,q,"Z",0);r00=component(p,q,"R00",1);r10=component(p,q,"R10",0);r20=component(p,q,"R20",0);r21=component(p,q,"R21",0);r22=component(p,q,"R22",1);r11=component(p,q,"R11",1);r12=component(p,q,"R12",0);{float pitch=asinf(fmaxf(-1.0f,fminf(1.0f,-r20)));float cp=cosf(pitch);if(fabsf(cp)>0.001f){*rx=atan2f(r21,r22)*57.2957795f;*ry=pitch*57.2957795f;*rz=atan2f(r10,r00)*57.2957795f;}else{*rx=atan2f(-r12,r11)*57.2957795f;*ry=pitch*57.2957795f;*rz=0;}}}
static uint32_t property_color(const char* begin,const char* end){char text[64];char* ep;unsigned long packed;if(named_text(begin,end,"Color3uint8","Color3uint8",text,sizeof(text))){packed=strtoul(text,&ep,10);if(ep!=text)return (uint32_t)packed;}if(named_text(begin,end,"Color3","Color3",text,sizeof(text))){packed=strtoul(text,&ep,10);if(ep!=text)return (uint32_t)packed;}return 0x808080ffu;}
nds_result nds_rbxlx_load(const char* path,nds_instance** out_root){char* data;size_t size;const char* p;const char* end;nds_instance* root;if(!path||!out_root)return NDS_ERR_INVALID_ARG;*out_root=NULL;data=read_file(path,&size);if(!data)return NDS_ERR_IO;if(strncmp(data,"<roblox",7)!=0){free(data);return NDS_ERR_IO;}root=nds_instance_create(NDS_CLASS_DATAMODEL,"ImportedPlace");if(!root){free(data);return NDS_ERR_UNKNOWN;}p=data;end=data+size;while((p=strstr(p,"<Item"))!=NULL&&p<end){const char* item_end;char class_name[64];char name[256];nds_instance* object;nds_part_properties props;float x,y,z,rx,ry,rz,sx,sy,sz;const char* size_tag;const char* size_end;if(p>data&&p[-1]=='/'){p+=5;continue;}item_end=find_item_end(p,end);if(!item_end)break;if(!attr_value(p,item_end,"class",class_name,sizeof(class_name))){p=item_end;continue;}if(strcmp(class_name,"Part")!=0&&strcmp(class_name,"SpawnLocation")!=0&&strcmp(class_name,"WedgePart")!=0&&strcmp(class_name,"CornerWedgePart")!=0&&strcmp(class_name,"TrussPart")!=0&&strcmp(class_name,"MeshPart")!=0){p=item_end;continue;}if(!named_text(p,item_end,"string","Name",name,sizeof(name)))snprintf(name,sizeof(name),"ImportedPart");object=nds_instance_create(strcmp(class_name,"SpawnLocation")==0?NDS_CLASS_SPAWN_POINT:NDS_CLASS_PART,name);if(!object){nds_instance_destroy(root);free(data);return NDS_ERR_UNKNOWN;}if(nds_part_get_properties(object,&props)!=NDS_OK){nds_instance_destroy(object);p=item_end;continue;}cframe(p,item_end,&x,&y,&z,&rx,&ry,&rz);sx=sy=sz=1;size_tag=strstr(p,"<Vector3 name=\"size\"");if(size_tag&&size_tag<item_end){size_end=strstr(size_tag,"</Vector3>");if(size_end&&size_end<item_end){sx=component(size_tag,size_end,"X",1);sy=component(size_tag,size_end,"Y",1);sz=component(size_tag,size_end,"Z",1);}}props.position=(nds_vec3){x,y,z};props.size=(nds_vec3){sx>0?sx:1,sy>0?sy:1,sz>0?sz:1};props.rotation=(nds_vec3){rx,ry,rz};props.color_rgba=property_color(p,item_end);props.transparency=named_float(p,item_end,"float","Transparency",0);props.reflectance=named_float(p,item_end,"float","Reflectance",0);props.anchored=named_bool(p,item_end,"Anchored",1);props.can_collide=named_bool(p,item_end,"CanCollide",1);if(nds_part_set_properties(object,&props)!=NDS_OK||nds_instance_set_parent(object,root)!=NDS_OK){nds_instance_destroy(object);nds_instance_destroy(root);free(data);return NDS_ERR_IO;}p=item_end;}free(data);*out_root=root;return NDS_OK;}
